title: "[Suggestions] 請使用與內容直接相關且詳細的標題"
labels: ["suggestions"]
body:
  - type: checkboxes
    id: checks1
    attributes:
      label: "我已確認："
      options:
        - label: "Discussions 頁面中沒有類似相關主題。"
          required: true
  - type: checkboxes
    id: checks2
    attributes:
      label: "我瞭解："
      options:
        - label: "在此發表建議不代表其必定會成為此模組的修改方向。"
          required: true
  - type: textarea
    id: what-happened
    attributes:
      label: "我的建議："
      description: 輸入與主題直接相關且詳細的文字敘述，盡量勿只有圖片以便以文字搜尋。
    validations:
      required: true
      
