name: "其他問題/Other-issue"
description: 遊戲崩潰、錯誤訊息、其它問題。The game crashed, errors popping, etc.
title: "[Other-issue]"
labels: ["其它問題/other issue", "triage"]
projects: ["octo-org/1", "octo-org/44"]
body:
  - type: textarea
    id: what-happened
    attributes:
      label: "我遇到了以下問題:"
      description: 輸入與問題直接相關且詳細的敘述，可附圖片但勿只有圖片以便搜尋。發送前能以 Preview 先行檢視。
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
   - type: checkboxes
    id: checks
    attributes:
      label: "Disclaimers"
      options:
        - label: "我已確認 Issues 頁面中沒有同樣的問題尚為Open。"
          required: true
          
