name: "其他問題/Other Issue"
description: 回報不為其他分類的問題。(No fitting issue types)
title: "[Other Issue] 請使用與內容直接相關且詳細的標題"
labels: ["其它問題/other issue"]
body:
  - type: checkboxes
    id: checks
    attributes:
      label: "我已確認："
      options:
        - label: "Issues 頁面中沒有尚為 Open 的相關主題。"
          required: true
  - type: textarea
    id: what-happened
    attributes:
      label: "我的問題："
      description: 輸入與問題直接相關且詳細的文字敘述，盡量勿只有圖片以便以文字搜尋。
    validations:
      required: true
      
