name: "其他問題/Other-issue"
description: 跳出錯誤訊息、不為其他種類的問題。(Errors popping, no fitting issue types, etc.)
title: "[Other-issue] 請使用與內容直接相關且詳細的標題"
labels: ["其它問題/other issue"]
body:
  - type: checkboxes
    id: checks
    attributes:
      label: ""
      options:
        - label: "我已確認 Issues 頁面中沒有尚為Open的相關主題。"
          required: true
  - type: textarea
    id: what-happened
    attributes:
      label: "我遇到了以下問題:"
      description: 輸入與問題直接相關且詳細的文字敘述，盡量勿只有圖片以便以文字搜尋。發送前能以 Preview 先行檢視。
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  
