name: For testing only, don't use this.
description: 測試用，請勿選取。
title: "[TEST] #，測試標題"
labels: [invalid, wontfix]
body:
- type: checkboxes
  attributes:
    label: 勾選框框
    options:
    - label: 我已確認 Issues 頁面尚為Open的問題之中沒有同樣的問題已被回報。
      required: true
- type: textarea
  attributes:
    label: 文字區域
    description: 輸入與錯誤直接相關且詳細的敘述，可附圖片但勿只有圖片以便搜尋。
    placeholder: |
      1. In this environment...
      2. With this config...
      3. Run '...'
      4. See error...
  validations:
    required: true
