name: For testing only, don't use this.
description: 測試用，請勿選取。
title: "[TEST] #，測試標題"
labels: [invalid, wontfix]
body:
- type: checkboxes
  attributes:
    label: 你好嗎
    description: Please search to see if an issue already exists for the bug you encountered.
    options:
    - label: I have searched the existing issues
      required: true
- type: textarea
  attributes:
    label: 試試看
    description: Steps to reproduce the behavior.
    placeholder: |
      1. In this environment...
      2. With this config...
      3. Run '...'
      4. See error...
  validations:
    required: true
