name: For testing only, don't use this.
description: 測試用，請勿選取。
title: "[TEST] #，測試標題"
labels: [invalid, wontfix]
body:
- type: checkboxes
  attributes:
    label: ㄅㄆㄇㄈ
    description: ㄅㄆㄇㄈ
    options:
    - label: ㄉㄊㄋㄌ
      required: true
- type: textarea
  attributes:
    label: ㄅㄆㄇㄈ
    description: ㄅㄆㄇㄈ
    placeholder: |
    1. ㄅ
    2. ㄆ
    3. ㄇ
  validations:
    required: true
